//// <auto-generated />
//using Cache.Models;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace Cache.Migrations
//{
//    [DbContext(typeof(Context))]
//    [Migration("20240828091053_AddUrunsTableTrigger")]
//    partial class AddUrunsTableTrigger
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.8")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("Cache.Models.Kategori", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Kategoris");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            Isim = "Kategori-1"
//                        },
//                        new
//                        {
//                            Id = 2,
//                            Isim = "Kategori-2"
//                        },
//                        new
//                        {
//                            Id = 3,
//                            Isim = "Kategori-3"
//                        },
//                        new
//                        {
//                            Id = 4,
//                            Isim = "Kategori-4"
//                        },
//                        new
//                        {
//                            Id = 5,
//                            Isim = "Kategori-5"
//                        },
//                        new
//                        {
//                            Id = 6,
//                            Isim = "Kategori-6"
//                        },
//                        new
//                        {
//                            Id = 7,
//                            Isim = "Kategori-7"
//                        },
//                        new
//                        {
//                            Id = 8,
//                            Isim = "Kategori-8"
//                        },
//                        new
//                        {
//                            Id = 9,
//                            Isim = "Kategori-9"
//                        },
//                        new
//                        {
//                            Id = 10,
//                            Isim = "Kategori-10"
//                        },
//                        new
//                        {
//                            Id = 11,
//                            Isim = "Kategori-11"
//                        },
//                        new
//                        {
//                            Id = 12,
//                            Isim = "Kategori-12"
//                        },
//                        new
//                        {
//                            Id = 13,
//                            Isim = "Kategori-13"
//                        },
//                        new
//                        {
//                            Id = 14,
//                            Isim = "Kategori-14"
//                        },
//                        new
//                        {
//                            Id = 15,
//                            Isim = "Kategori-15"
//                        },
//                        new
//                        {
//                            Id = 16,
//                            Isim = "Kategori-16"
//                        },
//                        new
//                        {
//                            Id = 17,
//                            Isim = "Kategori-17"
//                        },
//                        new
//                        {
//                            Id = 18,
//                            Isim = "Kategori-18"
//                        },
//                        new
//                        {
//                            Id = 19,
//                            Isim = "Kategori-19"
//                        },
//                        new
//                        {
//                            Id = 20,
//                            Isim = "Kategori-20"
//                        },
//                        new
//                        {
//                            Id = 21,
//                            Isim = "Kategori-21"
//                        },
//                        new
//                        {
//                            Id = 22,
//                            Isim = "Kategori-22"
//                        },
//                        new
//                        {
//                            Id = 23,
//                            Isim = "Kategori-23"
//                        },
//                        new
//                        {
//                            Id = 24,
//                            Isim = "Kategori-24"
//                        },
//                        new
//                        {
//                            Id = 25,
//                            Isim = "Kategori-25"
//                        },
//                        new
//                        {
//                            Id = 26,
//                            Isim = "Kategori-26"
//                        },
//                        new
//                        {
//                            Id = 27,
//                            Isim = "Kategori-27"
//                        },
//                        new
//                        {
//                            Id = 28,
//                            Isim = "Kategori-28"
//                        },
//                        new
//                        {
//                            Id = 29,
//                            Isim = "Kategori-29"
//                        },
//                        new
//                        {
//                            Id = 30,
//                            Isim = "Kategori-30"
//                        },
//                        new
//                        {
//                            Id = 31,
//                            Isim = "Kategori-31"
//                        },
//                        new
//                        {
//                            Id = 32,
//                            Isim = "Kategori-32"
//                        },
//                        new
//                        {
//                            Id = 33,
//                            Isim = "Kategori-33"
//                        },
//                        new
//                        {
//                            Id = 34,
//                            Isim = "Kategori-34"
//                        },
//                        new
//                        {
//                            Id = 35,
//                            Isim = "Kategori-35"
//                        },
//                        new
//                        {
//                            Id = 36,
//                            Isim = "Kategori-36"
//                        },
//                        new
//                        {
//                            Id = 37,
//                            Isim = "Kategori-37"
//                        },
//                        new
//                        {
//                            Id = 38,
//                            Isim = "Kategori-38"
//                        },
//                        new
//                        {
//                            Id = 39,
//                            Isim = "Kategori-39"
//                        },
//                        new
//                        {
//                            Id = 40,
//                            Isim = "Kategori-40"
//                        },
//                        new
//                        {
//                            Id = 41,
//                            Isim = "Kategori-41"
//                        },
//                        new
//                        {
//                            Id = 42,
//                            Isim = "Kategori-42"
//                        },
//                        new
//                        {
//                            Id = 43,
//                            Isim = "Kategori-43"
//                        },
//                        new
//                        {
//                            Id = 44,
//                            Isim = "Kategori-44"
//                        },
//                        new
//                        {
//                            Id = 45,
//                            Isim = "Kategori-45"
//                        },
//                        new
//                        {
//                            Id = 46,
//                            Isim = "Kategori-46"
//                        },
//                        new
//                        {
//                            Id = 47,
//                            Isim = "Kategori-47"
//                        },
//                        new
//                        {
//                            Id = 48,
//                            Isim = "Kategori-48"
//                        },
//                        new
//                        {
//                            Id = 49,
//                            Isim = "Kategori-49"
//                        },
//                        new
//                        {
//                            Id = 50,
//                            Isim = "Kategori-50"
//                        },
//                        new
//                        {
//                            Id = 51,
//                            Isim = "Kategori-51"
//                        },
//                        new
//                        {
//                            Id = 52,
//                            Isim = "Kategori-52"
//                        },
//                        new
//                        {
//                            Id = 53,
//                            Isim = "Kategori-53"
//                        },
//                        new
//                        {
//                            Id = 54,
//                            Isim = "Kategori-54"
//                        },
//                        new
//                        {
//                            Id = 55,
//                            Isim = "Kategori-55"
//                        },
//                        new
//                        {
//                            Id = 56,
//                            Isim = "Kategori-56"
//                        },
//                        new
//                        {
//                            Id = 57,
//                            Isim = "Kategori-57"
//                        },
//                        new
//                        {
//                            Id = 58,
//                            Isim = "Kategori-58"
//                        },
//                        new
//                        {
//                            Id = 59,
//                            Isim = "Kategori-59"
//                        },
//                        new
//                        {
//                            Id = 60,
//                            Isim = "Kategori-60"
//                        },
//                        new
//                        {
//                            Id = 61,
//                            Isim = "Kategori-61"
//                        },
//                        new
//                        {
//                            Id = 62,
//                            Isim = "Kategori-62"
//                        },
//                        new
//                        {
//                            Id = 63,
//                            Isim = "Kategori-63"
//                        },
//                        new
//                        {
//                            Id = 64,
//                            Isim = "Kategori-64"
//                        },
//                        new
//                        {
//                            Id = 65,
//                            Isim = "Kategori-65"
//                        },
//                        new
//                        {
//                            Id = 66,
//                            Isim = "Kategori-66"
//                        },
//                        new
//                        {
//                            Id = 67,
//                            Isim = "Kategori-67"
//                        },
//                        new
//                        {
//                            Id = 68,
//                            Isim = "Kategori-68"
//                        },
//                        new
//                        {
//                            Id = 69,
//                            Isim = "Kategori-69"
//                        },
//                        new
//                        {
//                            Id = 70,
//                            Isim = "Kategori-70"
//                        },
//                        new
//                        {
//                            Id = 71,
//                            Isim = "Kategori-71"
//                        },
//                        new
//                        {
//                            Id = 72,
//                            Isim = "Kategori-72"
//                        },
//                        new
//                        {
//                            Id = 73,
//                            Isim = "Kategori-73"
//                        },
//                        new
//                        {
//                            Id = 74,
//                            Isim = "Kategori-74"
//                        },
//                        new
//                        {
//                            Id = 75,
//                            Isim = "Kategori-75"
//                        },
//                        new
//                        {
//                            Id = 76,
//                            Isim = "Kategori-76"
//                        },
//                        new
//                        {
//                            Id = 77,
//                            Isim = "Kategori-77"
//                        },
//                        new
//                        {
//                            Id = 78,
//                            Isim = "Kategori-78"
//                        },
//                        new
//                        {
//                            Id = 79,
//                            Isim = "Kategori-79"
//                        },
//                        new
//                        {
//                            Id = 80,
//                            Isim = "Kategori-80"
//                        },
//                        new
//                        {
//                            Id = 81,
//                            Isim = "Kategori-81"
//                        },
//                        new
//                        {
//                            Id = 82,
//                            Isim = "Kategori-82"
//                        },
//                        new
//                        {
//                            Id = 83,
//                            Isim = "Kategori-83"
//                        },
//                        new
//                        {
//                            Id = 84,
//                            Isim = "Kategori-84"
//                        },
//                        new
//                        {
//                            Id = 85,
//                            Isim = "Kategori-85"
//                        },
//                        new
//                        {
//                            Id = 86,
//                            Isim = "Kategori-86"
//                        },
//                        new
//                        {
//                            Id = 87,
//                            Isim = "Kategori-87"
//                        },
//                        new
//                        {
//                            Id = 88,
//                            Isim = "Kategori-88"
//                        },
//                        new
//                        {
//                            Id = 89,
//                            Isim = "Kategori-89"
//                        },
//                        new
//                        {
//                            Id = 90,
//                            Isim = "Kategori-90"
//                        },
//                        new
//                        {
//                            Id = 91,
//                            Isim = "Kategori-91"
//                        },
//                        new
//                        {
//                            Id = 92,
//                            Isim = "Kategori-92"
//                        },
//                        new
//                        {
//                            Id = 93,
//                            Isim = "Kategori-93"
//                        },
//                        new
//                        {
//                            Id = 94,
//                            Isim = "Kategori-94"
//                        },
//                        new
//                        {
//                            Id = 95,
//                            Isim = "Kategori-95"
//                        },
//                        new
//                        {
//                            Id = 96,
//                            Isim = "Kategori-96"
//                        },
//                        new
//                        {
//                            Id = 97,
//                            Isim = "Kategori-97"
//                        },
//                        new
//                        {
//                            Id = 98,
//                            Isim = "Kategori-98"
//                        },
//                        new
//                        {
//                            Id = 99,
//                            Isim = "Kategori-99"
//                        },
//                        new
//                        {
//                            Id = 100,
//                            Isim = "Kategori-100"
//                        },
//                        new
//                        {
//                            Id = 101,
//                            Isim = "Kategori-101"
//                        },
//                        new
//                        {
//                            Id = 102,
//                            Isim = "Kategori-102"
//                        },
//                        new
//                        {
//                            Id = 103,
//                            Isim = "Kategori-103"
//                        },
//                        new
//                        {
//                            Id = 104,
//                            Isim = "Kategori-104"
//                        },
//                        new
//                        {
//                            Id = 105,
//                            Isim = "Kategori-105"
//                        },
//                        new
//                        {
//                            Id = 106,
//                            Isim = "Kategori-106"
//                        },
//                        new
//                        {
//                            Id = 107,
//                            Isim = "Kategori-107"
//                        },
//                        new
//                        {
//                            Id = 108,
//                            Isim = "Kategori-108"
//                        },
//                        new
//                        {
//                            Id = 109,
//                            Isim = "Kategori-109"
//                        },
//                        new
//                        {
//                            Id = 110,
//                            Isim = "Kategori-110"
//                        },
//                        new
//                        {
//                            Id = 111,
//                            Isim = "Kategori-111"
//                        },
//                        new
//                        {
//                            Id = 112,
//                            Isim = "Kategori-112"
//                        },
//                        new
//                        {
//                            Id = 113,
//                            Isim = "Kategori-113"
//                        },
//                        new
//                        {
//                            Id = 114,
//                            Isim = "Kategori-114"
//                        },
//                        new
//                        {
//                            Id = 115,
//                            Isim = "Kategori-115"
//                        },
//                        new
//                        {
//                            Id = 116,
//                            Isim = "Kategori-116"
//                        },
//                        new
//                        {
//                            Id = 117,
//                            Isim = "Kategori-117"
//                        },
//                        new
//                        {
//                            Id = 118,
//                            Isim = "Kategori-118"
//                        },
//                        new
//                        {
//                            Id = 119,
//                            Isim = "Kategori-119"
//                        },
//                        new
//                        {
//                            Id = 120,
//                            Isim = "Kategori-120"
//                        },
//                        new
//                        {
//                            Id = 121,
//                            Isim = "Kategori-121"
//                        },
//                        new
//                        {
//                            Id = 122,
//                            Isim = "Kategori-122"
//                        },
//                        new
//                        {
//                            Id = 123,
//                            Isim = "Kategori-123"
//                        },
//                        new
//                        {
//                            Id = 124,
//                            Isim = "Kategori-124"
//                        },
//                        new
//                        {
//                            Id = 125,
//                            Isim = "Kategori-125"
//                        },
//                        new
//                        {
//                            Id = 126,
//                            Isim = "Kategori-126"
//                        },
//                        new
//                        {
//                            Id = 127,
//                            Isim = "Kategori-127"
//                        },
//                        new
//                        {
//                            Id = 128,
//                            Isim = "Kategori-128"
//                        },
//                        new
//                        {
//                            Id = 129,
//                            Isim = "Kategori-129"
//                        },
//                        new
//                        {
//                            Id = 130,
//                            Isim = "Kategori-130"
//                        },
//                        new
//                        {
//                            Id = 131,
//                            Isim = "Kategori-131"
//                        },
//                        new
//                        {
//                            Id = 132,
//                            Isim = "Kategori-132"
//                        },
//                        new
//                        {
//                            Id = 133,
//                            Isim = "Kategori-133"
//                        },
//                        new
//                        {
//                            Id = 134,
//                            Isim = "Kategori-134"
//                        },
//                        new
//                        {
//                            Id = 135,
//                            Isim = "Kategori-135"
//                        },
//                        new
//                        {
//                            Id = 136,
//                            Isim = "Kategori-136"
//                        },
//                        new
//                        {
//                            Id = 137,
//                            Isim = "Kategori-137"
//                        },
//                        new
//                        {
//                            Id = 138,
//                            Isim = "Kategori-138"
//                        },
//                        new
//                        {
//                            Id = 139,
//                            Isim = "Kategori-139"
//                        },
//                        new
//                        {
//                            Id = 140,
//                            Isim = "Kategori-140"
//                        },
//                        new
//                        {
//                            Id = 141,
//                            Isim = "Kategori-141"
//                        },
//                        new
//                        {
//                            Id = 142,
//                            Isim = "Kategori-142"
//                        },
//                        new
//                        {
//                            Id = 143,
//                            Isim = "Kategori-143"
//                        },
//                        new
//                        {
//                            Id = 144,
//                            Isim = "Kategori-144"
//                        },
//                        new
//                        {
//                            Id = 145,
//                            Isim = "Kategori-145"
//                        },
//                        new
//                        {
//                            Id = 146,
//                            Isim = "Kategori-146"
//                        },
//                        new
//                        {
//                            Id = 147,
//                            Isim = "Kategori-147"
//                        },
//                        new
//                        {
//                            Id = 148,
//                            Isim = "Kategori-148"
//                        },
//                        new
//                        {
//                            Id = 149,
//                            Isim = "Kategori-149"
//                        },
//                        new
//                        {
//                            Id = 150,
//                            Isim = "Kategori-150"
//                        },
//                        new
//                        {
//                            Id = 151,
//                            Isim = "Kategori-151"
//                        },
//                        new
//                        {
//                            Id = 152,
//                            Isim = "Kategori-152"
//                        },
//                        new
//                        {
//                            Id = 153,
//                            Isim = "Kategori-153"
//                        },
//                        new
//                        {
//                            Id = 154,
//                            Isim = "Kategori-154"
//                        },
//                        new
//                        {
//                            Id = 155,
//                            Isim = "Kategori-155"
//                        },
//                        new
//                        {
//                            Id = 156,
//                            Isim = "Kategori-156"
//                        },
//                        new
//                        {
//                            Id = 157,
//                            Isim = "Kategori-157"
//                        },
//                        new
//                        {
//                            Id = 158,
//                            Isim = "Kategori-158"
//                        },
//                        new
//                        {
//                            Id = 159,
//                            Isim = "Kategori-159"
//                        },
//                        new
//                        {
//                            Id = 160,
//                            Isim = "Kategori-160"
//                        },
//                        new
//                        {
//                            Id = 161,
//                            Isim = "Kategori-161"
//                        },
//                        new
//                        {
//                            Id = 162,
//                            Isim = "Kategori-162"
//                        },
//                        new
//                        {
//                            Id = 163,
//                            Isim = "Kategori-163"
//                        },
//                        new
//                        {
//                            Id = 164,
//                            Isim = "Kategori-164"
//                        },
//                        new
//                        {
//                            Id = 165,
//                            Isim = "Kategori-165"
//                        },
//                        new
//                        {
//                            Id = 166,
//                            Isim = "Kategori-166"
//                        },
//                        new
//                        {
//                            Id = 167,
//                            Isim = "Kategori-167"
//                        },
//                        new
//                        {
//                            Id = 168,
//                            Isim = "Kategori-168"
//                        },
//                        new
//                        {
//                            Id = 169,
//                            Isim = "Kategori-169"
//                        },
//                        new
//                        {
//                            Id = 170,
//                            Isim = "Kategori-170"
//                        },
//                        new
//                        {
//                            Id = 171,
//                            Isim = "Kategori-171"
//                        },
//                        new
//                        {
//                            Id = 172,
//                            Isim = "Kategori-172"
//                        },
//                        new
//                        {
//                            Id = 173,
//                            Isim = "Kategori-173"
//                        },
//                        new
//                        {
//                            Id = 174,
//                            Isim = "Kategori-174"
//                        },
//                        new
//                        {
//                            Id = 175,
//                            Isim = "Kategori-175"
//                        },
//                        new
//                        {
//                            Id = 176,
//                            Isim = "Kategori-176"
//                        },
//                        new
//                        {
//                            Id = 177,
//                            Isim = "Kategori-177"
//                        },
//                        new
//                        {
//                            Id = 178,
//                            Isim = "Kategori-178"
//                        },
//                        new
//                        {
//                            Id = 179,
//                            Isim = "Kategori-179"
//                        },
//                        new
//                        {
//                            Id = 180,
//                            Isim = "Kategori-180"
//                        },
//                        new
//                        {
//                            Id = 181,
//                            Isim = "Kategori-181"
//                        },
//                        new
//                        {
//                            Id = 182,
//                            Isim = "Kategori-182"
//                        },
//                        new
//                        {
//                            Id = 183,
//                            Isim = "Kategori-183"
//                        },
//                        new
//                        {
//                            Id = 184,
//                            Isim = "Kategori-184"
//                        },
//                        new
//                        {
//                            Id = 185,
//                            Isim = "Kategori-185"
//                        },
//                        new
//                        {
//                            Id = 186,
//                            Isim = "Kategori-186"
//                        },
//                        new
//                        {
//                            Id = 187,
//                            Isim = "Kategori-187"
//                        },
//                        new
//                        {
//                            Id = 188,
//                            Isim = "Kategori-188"
//                        },
//                        new
//                        {
//                            Id = 189,
//                            Isim = "Kategori-189"
//                        },
//                        new
//                        {
//                            Id = 190,
//                            Isim = "Kategori-190"
//                        },
//                        new
//                        {
//                            Id = 191,
//                            Isim = "Kategori-191"
//                        },
//                        new
//                        {
//                            Id = 192,
//                            Isim = "Kategori-192"
//                        },
//                        new
//                        {
//                            Id = 193,
//                            Isim = "Kategori-193"
//                        },
//                        new
//                        {
//                            Id = 194,
//                            Isim = "Kategori-194"
//                        },
//                        new
//                        {
//                            Id = 195,
//                            Isim = "Kategori-195"
//                        },
//                        new
//                        {
//                            Id = 196,
//                            Isim = "Kategori-196"
//                        },
//                        new
//                        {
//                            Id = 197,
//                            Isim = "Kategori-197"
//                        },
//                        new
//                        {
//                            Id = 198,
//                            Isim = "Kategori-198"
//                        },
//                        new
//                        {
//                            Id = 199,
//                            Isim = "Kategori-199"
//                        },
//                        new
//                        {
//                            Id = 200,
//                            Isim = "Kategori-200"
//                        });
//                });

//            modelBuilder.Entity("Cache.Models.Urun", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("KategoriId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("KategoriId");

//                    b.ToTable("Uruns", null, t =>
//                        {
//                            t.HasTrigger("UrunsTableChangeTrigger");
//                        });

//                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            Isim = "Urun-1",
//                            KategoriId = 1
//                        },
//                        new
//                        {
//                            Id = 2,
//                            Isim = "Urun-2",
//                            KategoriId = 2
//                        },
//                        new
//                        {
//                            Id = 3,
//                            Isim = "Urun-3",
//                            KategoriId = 3
//                        },
//                        new
//                        {
//                            Id = 4,
//                            Isim = "Urun-4",
//                            KategoriId = 4
//                        },
//                        new
//                        {
//                            Id = 5,
//                            Isim = "Urun-5",
//                            KategoriId = 5
//                        },
//                        new
//                        {
//                            Id = 6,
//                            Isim = "Urun-6",
//                            KategoriId = 6
//                        },
//                        new
//                        {
//                            Id = 7,
//                            Isim = "Urun-7",
//                            KategoriId = 7
//                        },
//                        new
//                        {
//                            Id = 8,
//                            Isim = "Urun-8",
//                            KategoriId = 8
//                        },
//                        new
//                        {
//                            Id = 9,
//                            Isim = "Urun-9",
//                            KategoriId = 9
//                        },
//                        new
//                        {
//                            Id = 10,
//                            Isim = "Urun-10",
//                            KategoriId = 10
//                        },
//                        new
//                        {
//                            Id = 11,
//                            Isim = "Urun-11",
//                            KategoriId = 11
//                        },
//                        new
//                        {
//                            Id = 12,
//                            Isim = "Urun-12",
//                            KategoriId = 12
//                        },
//                        new
//                        {
//                            Id = 13,
//                            Isim = "Urun-13",
//                            KategoriId = 13
//                        },
//                        new
//                        {
//                            Id = 14,
//                            Isim = "Urun-14",
//                            KategoriId = 14
//                        },
//                        new
//                        {
//                            Id = 15,
//                            Isim = "Urun-15",
//                            KategoriId = 15
//                        },
//                        new
//                        {
//                            Id = 16,
//                            Isim = "Urun-16",
//                            KategoriId = 16
//                        },
//                        new
//                        {
//                            Id = 17,
//                            Isim = "Urun-17",
//                            KategoriId = 17
//                        },
//                        new
//                        {
//                            Id = 18,
//                            Isim = "Urun-18",
//                            KategoriId = 18
//                        },
//                        new
//                        {
//                            Id = 19,
//                            Isim = "Urun-19",
//                            KategoriId = 19
//                        },
//                        new
//                        {
//                            Id = 20,
//                            Isim = "Urun-20",
//                            KategoriId = 20
//                        },
//                        new
//                        {
//                            Id = 21,
//                            Isim = "Urun-21",
//                            KategoriId = 21
//                        },
//                        new
//                        {
//                            Id = 22,
//                            Isim = "Urun-22",
//                            KategoriId = 22
//                        },
//                        new
//                        {
//                            Id = 23,
//                            Isim = "Urun-23",
//                            KategoriId = 23
//                        },
//                        new
//                        {
//                            Id = 24,
//                            Isim = "Urun-24",
//                            KategoriId = 24
//                        },
//                        new
//                        {
//                            Id = 25,
//                            Isim = "Urun-25",
//                            KategoriId = 25
//                        },
//                        new
//                        {
//                            Id = 26,
//                            Isim = "Urun-26",
//                            KategoriId = 26
//                        },
//                        new
//                        {
//                            Id = 27,
//                            Isim = "Urun-27",
//                            KategoriId = 27
//                        },
//                        new
//                        {
//                            Id = 28,
//                            Isim = "Urun-28",
//                            KategoriId = 28
//                        },
//                        new
//                        {
//                            Id = 29,
//                            Isim = "Urun-29",
//                            KategoriId = 29
//                        },
//                        new
//                        {
//                            Id = 30,
//                            Isim = "Urun-30",
//                            KategoriId = 30
//                        },
//                        new
//                        {
//                            Id = 31,
//                            Isim = "Urun-31",
//                            KategoriId = 31
//                        },
//                        new
//                        {
//                            Id = 32,
//                            Isim = "Urun-32",
//                            KategoriId = 32
//                        },
//                        new
//                        {
//                            Id = 33,
//                            Isim = "Urun-33",
//                            KategoriId = 33
//                        },
//                        new
//                        {
//                            Id = 34,
//                            Isim = "Urun-34",
//                            KategoriId = 34
//                        },
//                        new
//                        {
//                            Id = 35,
//                            Isim = "Urun-35",
//                            KategoriId = 35
//                        },
//                        new
//                        {
//                            Id = 36,
//                            Isim = "Urun-36",
//                            KategoriId = 36
//                        },
//                        new
//                        {
//                            Id = 37,
//                            Isim = "Urun-37",
//                            KategoriId = 37
//                        },
//                        new
//                        {
//                            Id = 38,
//                            Isim = "Urun-38",
//                            KategoriId = 38
//                        },
//                        new
//                        {
//                            Id = 39,
//                            Isim = "Urun-39",
//                            KategoriId = 39
//                        },
//                        new
//                        {
//                            Id = 40,
//                            Isim = "Urun-40",
//                            KategoriId = 40
//                        },
//                        new
//                        {
//                            Id = 41,
//                            Isim = "Urun-41",
//                            KategoriId = 41
//                        },
//                        new
//                        {
//                            Id = 42,
//                            Isim = "Urun-42",
//                            KategoriId = 42
//                        },
//                        new
//                        {
//                            Id = 43,
//                            Isim = "Urun-43",
//                            KategoriId = 43
//                        },
//                        new
//                        {
//                            Id = 44,
//                            Isim = "Urun-44",
//                            KategoriId = 44
//                        },
//                        new
//                        {
//                            Id = 45,
//                            Isim = "Urun-45",
//                            KategoriId = 45
//                        },
//                        new
//                        {
//                            Id = 46,
//                            Isim = "Urun-46",
//                            KategoriId = 46
//                        },
//                        new
//                        {
//                            Id = 47,
//                            Isim = "Urun-47",
//                            KategoriId = 47
//                        },
//                        new
//                        {
//                            Id = 48,
//                            Isim = "Urun-48",
//                            KategoriId = 48
//                        },
//                        new
//                        {
//                            Id = 49,
//                            Isim = "Urun-49",
//                            KategoriId = 49
//                        },
//                        new
//                        {
//                            Id = 50,
//                            Isim = "Urun-50",
//                            KategoriId = 50
//                        },
//                        new
//                        {
//                            Id = 51,
//                            Isim = "Urun-51",
//                            KategoriId = 51
//                        },
//                        new
//                        {
//                            Id = 52,
//                            Isim = "Urun-52",
//                            KategoriId = 52
//                        },
//                        new
//                        {
//                            Id = 53,
//                            Isim = "Urun-53",
//                            KategoriId = 53
//                        },
//                        new
//                        {
//                            Id = 54,
//                            Isim = "Urun-54",
//                            KategoriId = 54
//                        },
//                        new
//                        {
//                            Id = 55,
//                            Isim = "Urun-55",
//                            KategoriId = 55
//                        },
//                        new
//                        {
//                            Id = 56,
//                            Isim = "Urun-56",
//                            KategoriId = 56
//                        },
//                        new
//                        {
//                            Id = 57,
//                            Isim = "Urun-57",
//                            KategoriId = 57
//                        },
//                        new
//                        {
//                            Id = 58,
//                            Isim = "Urun-58",
//                            KategoriId = 58
//                        },
//                        new
//                        {
//                            Id = 59,
//                            Isim = "Urun-59",
//                            KategoriId = 59
//                        },
//                        new
//                        {
//                            Id = 60,
//                            Isim = "Urun-60",
//                            KategoriId = 60
//                        },
//                        new
//                        {
//                            Id = 61,
//                            Isim = "Urun-61",
//                            KategoriId = 61
//                        },
//                        new
//                        {
//                            Id = 62,
//                            Isim = "Urun-62",
//                            KategoriId = 62
//                        },
//                        new
//                        {
//                            Id = 63,
//                            Isim = "Urun-63",
//                            KategoriId = 63
//                        },
//                        new
//                        {
//                            Id = 64,
//                            Isim = "Urun-64",
//                            KategoriId = 64
//                        },
//                        new
//                        {
//                            Id = 65,
//                            Isim = "Urun-65",
//                            KategoriId = 65
//                        },
//                        new
//                        {
//                            Id = 66,
//                            Isim = "Urun-66",
//                            KategoriId = 66
//                        },
//                        new
//                        {
//                            Id = 67,
//                            Isim = "Urun-67",
//                            KategoriId = 67
//                        },
//                        new
//                        {
//                            Id = 68,
//                            Isim = "Urun-68",
//                            KategoriId = 68
//                        },
//                        new
//                        {
//                            Id = 69,
//                            Isim = "Urun-69",
//                            KategoriId = 69
//                        },
//                        new
//                        {
//                            Id = 70,
//                            Isim = "Urun-70",
//                            KategoriId = 70
//                        },
//                        new
//                        {
//                            Id = 71,
//                            Isim = "Urun-71",
//                            KategoriId = 71
//                        },
//                        new
//                        {
//                            Id = 72,
//                            Isim = "Urun-72",
//                            KategoriId = 72
//                        },
//                        new
//                        {
//                            Id = 73,
//                            Isim = "Urun-73",
//                            KategoriId = 73
//                        },
//                        new
//                        {
//                            Id = 74,
//                            Isim = "Urun-74",
//                            KategoriId = 74
//                        },
//                        new
//                        {
//                            Id = 75,
//                            Isim = "Urun-75",
//                            KategoriId = 75
//                        },
//                        new
//                        {
//                            Id = 76,
//                            Isim = "Urun-76",
//                            KategoriId = 76
//                        },
//                        new
//                        {
//                            Id = 77,
//                            Isim = "Urun-77",
//                            KategoriId = 77
//                        },
//                        new
//                        {
//                            Id = 78,
//                            Isim = "Urun-78",
//                            KategoriId = 78
//                        },
//                        new
//                        {
//                            Id = 79,
//                            Isim = "Urun-79",
//                            KategoriId = 79
//                        },
//                        new
//                        {
//                            Id = 80,
//                            Isim = "Urun-80",
//                            KategoriId = 80
//                        },
//                        new
//                        {
//                            Id = 81,
//                            Isim = "Urun-81",
//                            KategoriId = 81
//                        },
//                        new
//                        {
//                            Id = 82,
//                            Isim = "Urun-82",
//                            KategoriId = 82
//                        },
//                        new
//                        {
//                            Id = 83,
//                            Isim = "Urun-83",
//                            KategoriId = 83
//                        },
//                        new
//                        {
//                            Id = 84,
//                            Isim = "Urun-84",
//                            KategoriId = 84
//                        },
//                        new
//                        {
//                            Id = 85,
//                            Isim = "Urun-85",
//                            KategoriId = 85
//                        },
//                        new
//                        {
//                            Id = 86,
//                            Isim = "Urun-86",
//                            KategoriId = 86
//                        },
//                        new
//                        {
//                            Id = 87,
//                            Isim = "Urun-87",
//                            KategoriId = 87
//                        },
//                        new
//                        {
//                            Id = 88,
//                            Isim = "Urun-88",
//                            KategoriId = 88
//                        },
//                        new
//                        {
//                            Id = 89,
//                            Isim = "Urun-89",
//                            KategoriId = 89
//                        },
//                        new
//                        {
//                            Id = 90,
//                            Isim = "Urun-90",
//                            KategoriId = 90
//                        },
//                        new
//                        {
//                            Id = 91,
//                            Isim = "Urun-91",
//                            KategoriId = 91
//                        },
//                        new
//                        {
//                            Id = 92,
//                            Isim = "Urun-92",
//                            KategoriId = 92
//                        },
//                        new
//                        {
//                            Id = 93,
//                            Isim = "Urun-93",
//                            KategoriId = 93
//                        },
//                        new
//                        {
//                            Id = 94,
//                            Isim = "Urun-94",
//                            KategoriId = 94
//                        },
//                        new
//                        {
//                            Id = 95,
//                            Isim = "Urun-95",
//                            KategoriId = 95
//                        },
//                        new
//                        {
//                            Id = 96,
//                            Isim = "Urun-96",
//                            KategoriId = 96
//                        },
//                        new
//                        {
//                            Id = 97,
//                            Isim = "Urun-97",
//                            KategoriId = 97
//                        },
//                        new
//                        {
//                            Id = 98,
//                            Isim = "Urun-98",
//                            KategoriId = 98
//                        },
//                        new
//                        {
//                            Id = 99,
//                            Isim = "Urun-99",
//                            KategoriId = 99
//                        },
//                        new
//                        {
//                            Id = 100,
//                            Isim = "Urun-100",
//                            KategoriId = 100
//                        },
//                        new
//                        {
//                            Id = 101,
//                            Isim = "Urun-101",
//                            KategoriId = 101
//                        },
//                        new
//                        {
//                            Id = 102,
//                            Isim = "Urun-102",
//                            KategoriId = 102
//                        },
//                        new
//                        {
//                            Id = 103,
//                            Isim = "Urun-103",
//                            KategoriId = 103
//                        },
//                        new
//                        {
//                            Id = 104,
//                            Isim = "Urun-104",
//                            KategoriId = 104
//                        },
//                        new
//                        {
//                            Id = 105,
//                            Isim = "Urun-105",
//                            KategoriId = 105
//                        },
//                        new
//                        {
//                            Id = 106,
//                            Isim = "Urun-106",
//                            KategoriId = 106
//                        },
//                        new
//                        {
//                            Id = 107,
//                            Isim = "Urun-107",
//                            KategoriId = 107
//                        },
//                        new
//                        {
//                            Id = 108,
//                            Isim = "Urun-108",
//                            KategoriId = 108
//                        },
//                        new
//                        {
//                            Id = 109,
//                            Isim = "Urun-109",
//                            KategoriId = 109
//                        },
//                        new
//                        {
//                            Id = 110,
//                            Isim = "Urun-110",
//                            KategoriId = 110
//                        },
//                        new
//                        {
//                            Id = 111,
//                            Isim = "Urun-111",
//                            KategoriId = 111
//                        },
//                        new
//                        {
//                            Id = 112,
//                            Isim = "Urun-112",
//                            KategoriId = 112
//                        },
//                        new
//                        {
//                            Id = 113,
//                            Isim = "Urun-113",
//                            KategoriId = 113
//                        },
//                        new
//                        {
//                            Id = 114,
//                            Isim = "Urun-114",
//                            KategoriId = 114
//                        },
//                        new
//                        {
//                            Id = 115,
//                            Isim = "Urun-115",
//                            KategoriId = 115
//                        },
//                        new
//                        {
//                            Id = 116,
//                            Isim = "Urun-116",
//                            KategoriId = 116
//                        },
//                        new
//                        {
//                            Id = 117,
//                            Isim = "Urun-117",
//                            KategoriId = 117
//                        },
//                        new
//                        {
//                            Id = 118,
//                            Isim = "Urun-118",
//                            KategoriId = 118
//                        },
//                        new
//                        {
//                            Id = 119,
//                            Isim = "Urun-119",
//                            KategoriId = 119
//                        },
//                        new
//                        {
//                            Id = 120,
//                            Isim = "Urun-120",
//                            KategoriId = 120
//                        },
//                        new
//                        {
//                            Id = 121,
//                            Isim = "Urun-121",
//                            KategoriId = 121
//                        },
//                        new
//                        {
//                            Id = 122,
//                            Isim = "Urun-122",
//                            KategoriId = 122
//                        },
//                        new
//                        {
//                            Id = 123,
//                            Isim = "Urun-123",
//                            KategoriId = 123
//                        },
//                        new
//                        {
//                            Id = 124,
//                            Isim = "Urun-124",
//                            KategoriId = 124
//                        },
//                        new
//                        {
//                            Id = 125,
//                            Isim = "Urun-125",
//                            KategoriId = 125
//                        },
//                        new
//                        {
//                            Id = 126,
//                            Isim = "Urun-126",
//                            KategoriId = 126
//                        },
//                        new
//                        {
//                            Id = 127,
//                            Isim = "Urun-127",
//                            KategoriId = 127
//                        },
//                        new
//                        {
//                            Id = 128,
//                            Isim = "Urun-128",
//                            KategoriId = 128
//                        },
//                        new
//                        {
//                            Id = 129,
//                            Isim = "Urun-129",
//                            KategoriId = 129
//                        },
//                        new
//                        {
//                            Id = 130,
//                            Isim = "Urun-130",
//                            KategoriId = 130
//                        },
//                        new
//                        {
//                            Id = 131,
//                            Isim = "Urun-131",
//                            KategoriId = 131
//                        },
//                        new
//                        {
//                            Id = 132,
//                            Isim = "Urun-132",
//                            KategoriId = 132
//                        },
//                        new
//                        {
//                            Id = 133,
//                            Isim = "Urun-133",
//                            KategoriId = 133
//                        },
//                        new
//                        {
//                            Id = 134,
//                            Isim = "Urun-134",
//                            KategoriId = 134
//                        },
//                        new
//                        {
//                            Id = 135,
//                            Isim = "Urun-135",
//                            KategoriId = 135
//                        },
//                        new
//                        {
//                            Id = 136,
//                            Isim = "Urun-136",
//                            KategoriId = 136
//                        },
//                        new
//                        {
//                            Id = 137,
//                            Isim = "Urun-137",
//                            KategoriId = 137
//                        },
//                        new
//                        {
//                            Id = 138,
//                            Isim = "Urun-138",
//                            KategoriId = 138
//                        },
//                        new
//                        {
//                            Id = 139,
//                            Isim = "Urun-139",
//                            KategoriId = 139
//                        },
//                        new
//                        {
//                            Id = 140,
//                            Isim = "Urun-140",
//                            KategoriId = 140
//                        },
//                        new
//                        {
//                            Id = 141,
//                            Isim = "Urun-141",
//                            KategoriId = 141
//                        },
//                        new
//                        {
//                            Id = 142,
//                            Isim = "Urun-142",
//                            KategoriId = 142
//                        },
//                        new
//                        {
//                            Id = 143,
//                            Isim = "Urun-143",
//                            KategoriId = 143
//                        },
//                        new
//                        {
//                            Id = 144,
//                            Isim = "Urun-144",
//                            KategoriId = 144
//                        },
//                        new
//                        {
//                            Id = 145,
//                            Isim = "Urun-145",
//                            KategoriId = 145
//                        },
//                        new
//                        {
//                            Id = 146,
//                            Isim = "Urun-146",
//                            KategoriId = 146
//                        },
//                        new
//                        {
//                            Id = 147,
//                            Isim = "Urun-147",
//                            KategoriId = 147
//                        },
//                        new
//                        {
//                            Id = 148,
//                            Isim = "Urun-148",
//                            KategoriId = 148
//                        },
//                        new
//                        {
//                            Id = 149,
//                            Isim = "Urun-149",
//                            KategoriId = 149
//                        },
//                        new
//                        {
//                            Id = 150,
//                            Isim = "Urun-150",
//                            KategoriId = 150
//                        },
//                        new
//                        {
//                            Id = 151,
//                            Isim = "Urun-151",
//                            KategoriId = 151
//                        },
//                        new
//                        {
//                            Id = 152,
//                            Isim = "Urun-152",
//                            KategoriId = 152
//                        },
//                        new
//                        {
//                            Id = 153,
//                            Isim = "Urun-153",
//                            KategoriId = 153
//                        },
//                        new
//                        {
//                            Id = 154,
//                            Isim = "Urun-154",
//                            KategoriId = 154
//                        },
//                        new
//                        {
//                            Id = 155,
//                            Isim = "Urun-155",
//                            KategoriId = 155
//                        },
//                        new
//                        {
//                            Id = 156,
//                            Isim = "Urun-156",
//                            KategoriId = 156
//                        },
//                        new
//                        {
//                            Id = 157,
//                            Isim = "Urun-157",
//                            KategoriId = 157
//                        },
//                        new
//                        {
//                            Id = 158,
//                            Isim = "Urun-158",
//                            KategoriId = 158
//                        },
//                        new
//                        {
//                            Id = 159,
//                            Isim = "Urun-159",
//                            KategoriId = 159
//                        },
//                        new
//                        {
//                            Id = 160,
//                            Isim = "Urun-160",
//                            KategoriId = 160
//                        },
//                        new
//                        {
//                            Id = 161,
//                            Isim = "Urun-161",
//                            KategoriId = 161
//                        },
//                        new
//                        {
//                            Id = 162,
//                            Isim = "Urun-162",
//                            KategoriId = 162
//                        },
//                        new
//                        {
//                            Id = 163,
//                            Isim = "Urun-163",
//                            KategoriId = 163
//                        },
//                        new
//                        {
//                            Id = 164,
//                            Isim = "Urun-164",
//                            KategoriId = 164
//                        },
//                        new
//                        {
//                            Id = 165,
//                            Isim = "Urun-165",
//                            KategoriId = 165
//                        },
//                        new
//                        {
//                            Id = 166,
//                            Isim = "Urun-166",
//                            KategoriId = 166
//                        },
//                        new
//                        {
//                            Id = 167,
//                            Isim = "Urun-167",
//                            KategoriId = 167
//                        },
//                        new
//                        {
//                            Id = 168,
//                            Isim = "Urun-168",
//                            KategoriId = 168
//                        },
//                        new
//                        {
//                            Id = 169,
//                            Isim = "Urun-169",
//                            KategoriId = 169
//                        },
//                        new
//                        {
//                            Id = 170,
//                            Isim = "Urun-170",
//                            KategoriId = 170
//                        },
//                        new
//                        {
//                            Id = 171,
//                            Isim = "Urun-171",
//                            KategoriId = 171
//                        },
//                        new
//                        {
//                            Id = 172,
//                            Isim = "Urun-172",
//                            KategoriId = 172
//                        },
//                        new
//                        {
//                            Id = 173,
//                            Isim = "Urun-173",
//                            KategoriId = 173
//                        },
//                        new
//                        {
//                            Id = 174,
//                            Isim = "Urun-174",
//                            KategoriId = 174
//                        },
//                        new
//                        {
//                            Id = 175,
//                            Isim = "Urun-175",
//                            KategoriId = 175
//                        },
//                        new
//                        {
//                            Id = 176,
//                            Isim = "Urun-176",
//                            KategoriId = 176
//                        },
//                        new
//                        {
//                            Id = 177,
//                            Isim = "Urun-177",
//                            KategoriId = 177
//                        },
//                        new
//                        {
//                            Id = 178,
//                            Isim = "Urun-178",
//                            KategoriId = 178
//                        },
//                        new
//                        {
//                            Id = 179,
//                            Isim = "Urun-179",
//                            KategoriId = 179
//                        },
//                        new
//                        {
//                            Id = 180,
//                            Isim = "Urun-180",
//                            KategoriId = 180
//                        },
//                        new
//                        {
//                            Id = 181,
//                            Isim = "Urun-181",
//                            KategoriId = 181
//                        },
//                        new
//                        {
//                            Id = 182,
//                            Isim = "Urun-182",
//                            KategoriId = 182
//                        },
//                        new
//                        {
//                            Id = 183,
//                            Isim = "Urun-183",
//                            KategoriId = 183
//                        },
//                        new
//                        {
//                            Id = 184,
//                            Isim = "Urun-184",
//                            KategoriId = 184
//                        },
//                        new
//                        {
//                            Id = 185,
//                            Isim = "Urun-185",
//                            KategoriId = 185
//                        },
//                        new
//                        {
//                            Id = 186,
//                            Isim = "Urun-186",
//                            KategoriId = 186
//                        },
//                        new
//                        {
//                            Id = 187,
//                            Isim = "Urun-187",
//                            KategoriId = 187
//                        },
//                        new
//                        {
//                            Id = 188,
//                            Isim = "Urun-188",
//                            KategoriId = 188
//                        },
//                        new
//                        {
//                            Id = 189,
//                            Isim = "Urun-189",
//                            KategoriId = 189
//                        },
//                        new
//                        {
//                            Id = 190,
//                            Isim = "Urun-190",
//                            KategoriId = 190
//                        },
//                        new
//                        {
//                            Id = 191,
//                            Isim = "Urun-191",
//                            KategoriId = 191
//                        },
//                        new
//                        {
//                            Id = 192,
//                            Isim = "Urun-192",
//                            KategoriId = 192
//                        },
//                        new
//                        {
//                            Id = 193,
//                            Isim = "Urun-193",
//                            KategoriId = 193
//                        },
//                        new
//                        {
//                            Id = 194,
//                            Isim = "Urun-194",
//                            KategoriId = 194
//                        },
//                        new
//                        {
//                            Id = 195,
//                            Isim = "Urun-195",
//                            KategoriId = 195
//                        },
//                        new
//                        {
//                            Id = 196,
//                            Isim = "Urun-196",
//                            KategoriId = 196
//                        },
//                        new
//                        {
//                            Id = 197,
//                            Isim = "Urun-197",
//                            KategoriId = 197
//                        },
//                        new
//                        {
//                            Id = 198,
//                            Isim = "Urun-198",
//                            KategoriId = 198
//                        },
//                        new
//                        {
//                            Id = 199,
//                            Isim = "Urun-199",
//                            KategoriId = 199
//                        },
//                        new
//                        {
//                            Id = 200,
//                            Isim = "Urun-200",
//                            KategoriId = 200
//                        });
//                });

//            modelBuilder.Entity("Cache.Models.Urun", b =>
//                {
//                    b.HasOne("Cache.Models.Kategori", "Kategori")
//                        .WithMany("Uruns")
//                        .HasForeignKey("KategoriId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Kategori");
//                });

//            modelBuilder.Entity("Cache.Models.Kategori", b =>
//                {
//                    b.Navigation("Uruns");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
